export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE';
export const PERSONS_VALUE_CHANGE = 'PERSONS_VALUE_CHANGE';
export const CATEGORIES_VALUE_CHANGE = 'CATEGORIES_VALUE_CHANGE';
export const MODES_VALUE_CHANGE = 'MODES_VALUE_CHANGE';
export const YEARS_VALUE_CHANGE = 'YEARS_VALUE_CHANGE';
export const LANGUAGES_VALUE_CHANGE = 'LANGUAGES_VALUE_CHANGE';
export const ORDER_VALUE_CHANGE = 'ORDER_VALUE_CHANGE';
