export const PLAY_MUSIC = "PLAY_MUSIC";
export const PAUSE_MUSIC = "PAUSE_MUSIC";
export const MUTE_MUSIC = "MUTE_MUSIC";
export const UNMUTE_MUSIC = "UNMUTE_MUSIC";
export const CHANGE_VOLUME = "CHANGE_VOLUME";
export const CHANGE_DURATION = "CHANGE_DURATION";
export const SET_PALYLIST = "SET_PALYLIST";
export const NEXT_MUSIC = "NEXT_MUSIC";
export const PREVIOUS_MUSIC = "PREVIOUS_MUSIC";
export const SET_CURRENT_URL = "SET_CURRENT_URL";
export const SET_IDS = "SET_IDS";
export const SET_PROGRESS = "SET_PROGRESS";
export const CHANGE_SHUFFLE = "CHANGE_SHUFFLE";
export const CHANGE_LOOP_STATE = "CHANGE_LOOP_STATE";
export const FORCE_STOP = "FORCE_STOP";
export const CHANGE_SHOW_MUSICBAR_ON_MOBILE_RATIO =
  "CHANGE_SHOW_MUSICBAR_ON_MOBILE_RATIO";
export const PLAY_THIS_LIST_FROM_MYPROFLIE = "PLAY_THIS_LIST_FROM_MYPROFLIE";
